spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/consultorio_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=clave_secreta_larga_de_al_menos_256_bits_b64encoded_o_alfanumerica_super_segura
jwt.expiration=2592000000

whatsapp.api.url=https://graph.facebook.com/v23.0
whatsapp.phone.number.id=1081354365060161
whatsapp.access.token=EAAUCPD0nRZBgBRFFHmI5ec52u0dw8JVMd9gWeT0lZB9KRsmkugMlZBng58jCJyonZABPy7dkTWqOXwcKg8TXu0N5EFQrKQhB82ZAbrq822H5ooT0hrvbHZB514Hqw7UErCyNPJfQb6mwxjeYshDw9ZCuy73fTac5MahuiCCYDPiqrgDp7Iz7DbhvIm4NZAjKZA4E9Y8vduj08xaNSdxCzzgQOAhzj1RfUE2LbgvCKHBHtNhluJh8FXlRL3ktMvLtZAyTZBqIQoekrWeNCZCnbuKSodZAxgsD5SwpwW81lkwZDZD
whatsapp.template.name=recordatorio_turno
whatsapp.template.language=es_AR
